services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "php artisan migrate && apache2-foreground"
